# Generated by Django 4.0.4 on 2022-07-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='direccion'),
        ),
    ]
