# Generated by Django 4.0.4 on 2022-07-01 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='especialidad',
        ),
    ]
