# Generated by Django 4.0.4 on 2022-07-09 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_usuario_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'categoria_usuario',
                'verbose_name_plural': 'categoria_usuario',
                'db_table': 'categoria_usuario',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.categoria_usuario'),
        ),
    ]
