# Generated by Django 4.0.4 on 2022-07-09 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_categoria_usuario_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria_usuario',
            options={'ordering': ['id'], 'verbose_name': 'tipo_usuario', 'verbose_name_plural': 'tipo_usuarios'},
        ),
        migrations.AlterModelTable(
            name='categoria_usuario',
            table='tipo_usuario',
        ),
    ]
