# Generated by Django 4.0.4 on 2022-07-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_categoria_usuario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='mail',
            field=models.EmailField(default=None, max_length=254, unique=True, verbose_name='mail'),
        ),
    ]
