# Generated by Django 4.0.4 on 2022-07-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_usuario_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='mail',
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True, verbose_name='email'),
        ),
    ]
