# Generated by Django 4.0.4 on 2022-06-13 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiambres', '0002_order_alter_category_id_orderitems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['id'], 'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitems',
            options={'ordering': ['id'], 'verbose_name': 'orderitem', 'verbose_name_plural': 'orderitems'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='user',
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='orderitems',
            table='orderitem',
        ),
    ]
