# Generated by Django 4.0.4 on 2022-06-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiambres', '0003_alter_order_options_alter_orderitems_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid_status',
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
