# Generated by Django 4.0.4 on 2022-06-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiambres', '0005_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
