# Generated by Django 4.0.4 on 2022-07-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiambres', '0008_rename_estado_tramite_iniciado_order_estado_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cantidad',
            field=models.FloatField(default=0),
        ),
    ]
