# Generated by Django 4.0.4 on 2022-07-09 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiambres', '0010_alter_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Unidadmedida',
                'verbose_name_plural': 'UnidadmedidaS',
                'db_table': 'unidadmedida',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='product',
            name='unidadmedida',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='fiambres.unidadmedida'),
        ),
    ]
