# Generated by Django 4.0.4 on 2022-07-09 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiambres', '0011_unidadmedida_remove_product_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unidadmedida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiambres.unidadmedida'),
        ),
    ]
