# Generated by Django 4.0.4 on 2022-07-09 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiambres', '0012_alter_product_unidadmedida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Precio',
                'verbose_name_plural': 'Precios',
                'db_table': 'precios',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='unidadmedida',
            options={'ordering': ['id'], 'verbose_name': 'unidadmedida', 'verbose_name_plural': 'unidadmedidas'},
        ),
        migrations.AddField(
            model_name='product',
            name='price_category',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='fiambres.precios'),
        ),
    ]
