# Generated by Django 4.0.4 on 2022-07-09 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiambres', '0013_precios_alter_unidadmedida_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiambres.precios'),
        ),
    ]
