# Generated by Django 4.0.4 on 2022-07-09 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_categoria_usuario_usuario_tipo_usuario'),
        ('fiambres', '0014_alter_product_price_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='precios',
            name='tipo_usuario',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.categoria_usuario'),
        ),
    ]
