# Generated by Django 4.0.4 on 2022-07-15 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_usuario_tipo_usuario'),
        ('fiambres', '0015_precios_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categoria_usuario',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.categoria_usuario'),
        ),
    ]
