# Generated by Django 4.0.4 on 2022-07-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiambres', '0016_product_categoria_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_category',
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
