# Generated by Django 4.0.4 on 2022-07-16 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiambres', '0017_remove_product_price_category_product_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
